#!/bin/sh

# first
# Этот файл просматривает все файлы в текущем каталоге
# для поиска строки POSIX, а затем выводит имена
# найденных файлов в стандартный вывод.

for file in *
do
    if grep -q POSIX $file
    then
        echo $file
    fi
done

exit 0